sudo: required
services: 
  - docker

before_install:
  - docker build -t pavan26devops/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pavan26devops/react-test npm test

after_success:
  - docker build -t pavan26devops/multi-client ./client
  - docker build -t pavan26devops/multi-nginx ./nginx
  - docker build -t pavan26devops/multi-server ./server
  - docker build -t pavan26devops/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # push those images to docker hub
  - docker push pavan26devops/multi-client
  - docker push pavan26devops/multi-nginx
  - docker push pavan26devops/multi-server
  - docker push pavan26devops/multi-worker
